version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "nuget"
      directory: "/ThemeConverter/ThemeConverter"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/ThemeConverter/ThemeConverterTests"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/ThemeConverter/ThemeTests/TestFiles/CSharpApp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/ThemeConverter/ThemeTests"
      schedule:
          interval: "daily"
      versioning-strategy: increase
